### ISSUE TITLE
docker时web容器启动失败

### ISSUE THREAD

**Issue by xiaobaidebai** [awake1t/linglong#10]
![图片](https://user-images.githubusercontent.com/48722325/108807795-30654780-75e0-11eb-9a65-2134cfc72829.png)
你好，我在启动docker时发现web容器报错，但我找不到相关的代码进行修改，已经在百度查找了解决方法，但还是时没能解决，只能打扰一下询问一下解决方案。报错如下：
[root@localhost linglong-master]# docker-compose up -d web
Building web
Step 1/11 : FROM node:latest as build-stage
 ---> 34c1219e2da7
Step 2/11 : MAINTAINER drunk_kk
 ---> Using cache
 ---> bbb20c283f31
Step 3/11 : RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
 ---> Using cache
 ---> 1102b372972c
Step 4/11 : WORKDIR /app
 ---> Using cache
 ---> 2f6b7f847d60
Step 5/11 : COPY . .
 ---> Using cache
 ---> 6f8b3db2fcb1
Step 6/11 : RUN rm -rf node_modules     && npm install node-sass     && cnpm run build
 ---> Running in 82c3765d6f32
npm notice 
npm notice New patch version of npm available! 7.5.3 -> 7.5.6
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.5.6>
npm notice Run `npm install -g npm@7.5.6` to update!
npm notice 
npm ERR! code EAI_AGAIN
npm ERR! syscall getaddrinfo
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npm.taobao.org/zrender/download/zrender-4.3.1.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npm.taobao.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-23T06_03_30_520Z-debug.log
ERROR: Service 'web' failed to build: The command '/bin/sh -c rm -rf node_modules     && npm install node-sass     && cnpm run build' returned a non-zero code: 1

**Comment by just805** [comment]
我用的 ubuntu 环境，一键就搞定了。

**Comment by awake1t** [comment]
辛苦告知下您的 电脑系统，版本，服务器位置(国内、国外)

**Comment by awake1t** [comment]
辛苦告知下您的 电脑系统，版本，服务器位置(国内、国外) 。 我有时间的时候复现下

**Comment by xiaobaidebai** [comment]
> 
> 
> 辛苦告知下您的 电脑系统，版本，服务器位置(国内、国外) 。 我有时间的时候复现下

系统版本：
CentOS Linux release 7.8.2003 (Core)

docker 版本
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

docker-comppose版本
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

服务器，本地虚拟机（我不知道这会不会有影响）

**Comment by xiaobaidebai** [comment]
> 
> 
> > 辛苦告知下您的 电脑系统，版本，服务器位置(国内、国外) 。 我有时间的时候复现下
> 
> 系统版本：
> CentOS Linux release 7.8.2003 (Core)
> 
> docker 版本
> Client: Docker Engine - Community
> Version: 19.03.13
> API version: 1.40
> Go version: go1.13.15
> Git commit: 4484c46d9d
> Built: Wed Sep 16 17:03:45 2020
> OS/Arch: linux/amd64
> Experimental: false
> 
> Server: Docker Engine - Community
> Engine:
> Version: 19.03.13
> API version: 1.40 (minimum version 1.12)
> Go version: go1.13.15
> Git commit: 4484c46d9d
> Built: Wed Sep 16 17:02:21 2020
> OS/Arch: linux/amd64
> Experimental: false
> containerd:
> Version: 1.3.7
> GitCommit: 8fba4e9a7d01810a393d5d25a3621dc101981175
> runc:
> Version: 1.0.0-rc10
> GitCommit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
> docker-init:
> Version: 0.18.0
> GitCommit: fec3683
> 
> docker-comppose版本
> docker-py version: 3.6.0
> CPython version: 3.6.7
> OpenSSL version: OpenSSL 1.1.0f 25 May 2017
> 
> 服务器，国内本地虚拟机（我不知道这会不会有影响）

**Comment by awake1t** [comment]
初步判断应该是网络问题，参考这两个试下能不能解决。

**Comment by awake1t** [comment]
初步判断应该是网络问题，参考这两个试下能不能解决。https://blog.csdn.net/Mr_OOO/article/details/81911784, https://segmentfault.com/q/1010000015910438,https://github.com/StefanScherer/dockerfiles-windows/issues/270

**Comment by hsr-123** [comment]
> 我用的ubuntu环境，一键就搞定了。

好兄弟，你用的什么版本的ubuntu啊

**Comment by awake1t** [comment]
已经更新部署方式，去掉了拉取npm的方式。分为本地部署、服务器部署。

**Comment by xiaobaidebai** [comment]
> 
> 
> 已经更新部署方式，去掉了拉取npm的方式。分为本地部署、服务器部署。

ok，我有空的时候再试试
