### ISSUE TITLE
docker 启动error

### ISSUE THREAD

**Issue by nmbboy** [awake1t/linglong#12]
大佬你好：
启动doker提示出错。百度没有结果。
linglong_mysql_1 is up-to-date
Starting linglong-server ... error

ERROR: for linglong-server  Cannot start service server: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./linglong\": permission denied": unknown

ERROR: for server  Cannot start service server: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./linglong\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by awake1t** [comment]
已经更新部署方式，去掉了拉取npm的方式。分为本地部署、服务器部署。
