### ISSUE TITLE
我在搭建过程中遇到了问题

### ISSUE THREAD

**Issue by fengxi-gyn** [awake1t/linglong#15]
![image](https://user-images.githubusercontent.com/65840666/108935470-b63ccd80-7688-11eb-96a7-bb8921c9f2ac.png)

我也不知道我的图片你能看见吗 我在搭建过程中 遇到了npm node等相关问题 解决一个又遇到了 一个我个人用的是阿里云的ubantu18.04 因为是小白 所以自己解决不了

**Comment by zhaodie** [comment]
我用阿里云ubutun20搭建也是出现这样的问题

**Comment by awake1t** [comment]
收到反馈，我自己测试是在国外服务器。 在 阿里云上可能有问题，回头我自己复现下。 感谢反馈

**Comment by sttscc** [comment]
> ![image](https://user-images.githubusercontent.com/65840666/108935470-b63ccd80-7688-11eb-96a7-bb8921c9f2ac.png)
> 
> 我也不知道我的图片你能看见吗 我在搭建过程中 遇到了npm node等相关问题 解决一个又遇到了 一个我个人用的是阿里云的ubantu18.04 因为是小白 所以自己解决不了

我之前也出现了这样的问题，后面把web目录下面的Dockerfile中的cnpm改成npm就可以了

**Comment by fengxi-gyn** [comment]
改完npm之后第三步就挂了 不行
![image](https://user-images.githubusercontent.com/65840666/108968193-6a574c00-76bb-11eb-9d0e-40e6c0e743cf.png)

**Comment by fengxi-gyn** [comment]
我在本地尝试搭建成功，看来是环境的问题，没办法 谁让阿里云便宜嘞
![image](https://user-images.githubusercontent.com/65840666/108968460-c3bf7b00-76bb-11eb-8290-96e7dddc8c21.png)

**Comment by Xm17** [comment]
我也是啊！！！！
国外的vps，也不行
![image](https://user-images.githubusercontent.com/27048404/108978766-edc96b00-76c4-11eb-876d-6b9243ce1863.png)

**Comment by awake1t** [comment]
已经更新部署方式，去掉了拉取npm的方式。分为本地部署、服务器部署。
