### ISSUE TITLE
关于容器部署错误的建议

### ISSUE THREAD

**Issue by xiaobaidebai** [awake1t/linglong#16]
个人有2种想法：
1、构建好镜像，放到文件夹中。缺点：文件压缩包会很大，但只需要按照好docker和docker-compose就行了，没有构建容器的错误；
2、构建好镜像，推到docker仓库中，通过docker push 下载，最后通过docker-compose文件调用。

**Comment by awake1t** [comment]
谢谢师傅建议。docker push 已开始就考虑过。因为我这个是前后端分离的项目， 前端每次都要请求后端的地址来进行操作。 所以前端里要获取后端的地址，这里为了节约大家的部署成本。我就用了compose来动态获取后端服务器地址。   因为前端WEB界面里后端服务器地址是变动的，所以目前 docker push 的方式，是没法实现的。因为构建好的镜像地址是写死的。 
当然，也可能是我不太懂docker。 我再研究研究。 如果师傅们看到有类似前后端分析的docker部署项目，请在底部留言，我去看看他们怎么做的。谢谢啦~
