### ISSUE TITLE
新增一个网段却无法开始扫描

### ISSUE THREAD

**Issue by shen1in** [awake1t/linglong#19]
例如，新增了一个132.97.0.0/16的网段，如附件，也更新了扫描设置，新增了任务列表，但是就是无法进行扫描，已经一两天了，还是扫描到了0个资产，请问下大佬，这种怎么解决呀~

**Comment by awake1t** [comment]
截图给我看下日志，还有设置。给点信息我好排查

**Comment by shen1in** [comment]
> 截图给我看下日志，还有设置。给点信息我好排查

我重装了一下，测试了一个小网段，发现可以扫描了，我再观察一下，有个问题想问一下您，就是如果只配置了扫描设置，任务列表为空会不会影响扫描的进行?

**Comment by awake1t** [comment]
不影响，扫描是资产发现。任务对资产进行操作，比如爆破。两者没有互斥关系
