### ISSUE TITLE
set 6 npm 报错 因为是国外的VPS 嘛

### ISSUE THREAD

**Issue by putinone** [awake1t/linglong#21]

**Comment by awake1t** [comment]
最新的项目，好像没有这个 SET 6了吧。如果有，请截图

**Comment by putinone** [comment]
我下载了最新的 服务都起来了 但是 登录时候跳转不进去 不知道又出什么问题了 
![image](https://user-images.githubusercontent.com/46947052/109944295-0cf17980-7d11-11eb-9ff2-161018ab7937.png)

**Comment by awake1t** [comment]
重新部署要删除之前的容器

**Comment by putinone** [comment]
> 重新部署要删除之前的容器
好的  感谢，非常感谢你的耐心解答
