### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by sinner-user** [awake1t/linglong#23]
师傅请问一下，我docker安装的时候出现这个错误是怎么回事呢
npm ERR! gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64-ARM/no-asm/include/openssl/opensslconfnpm ERR! gyp verb command remove [ '15.5.1' ]
npm ERR! gyp verb remove using node-gyp dir: /root/.node-gyp
npm ERR! gyp verb remove removing target version: 15.5.1
npm ERR! gyp verb remove removing development files for version: 15.5.1
npm ERR! gyp verb content checksum node-v15.5.1-headers.tar.gz e1837220591e22fdc53d367adf0cd6c539af89be51dba4e50d6d2d0ab0b477ab
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: aborted
npm ERR! gyp ERR! stack     at connResetException (node:internal/errors:631:14)
npm ERR! gyp ERR! stack     at TLSSocket.socketCloseListener (node:_http_client:434:19)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:388:22)
npm ERR! gyp ERR! stack     at node:net:666:12
npm ERR! gyp ERR! stack     at TCP.done (node:_tls_wrap:573:7)
npm ERR! gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
npm ERR! gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /app/node_modules/node-sass
npm ERR! gyp ERR! node -v v15.5.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-10T16_59_43_277Z-debug.log
ERROR: Service 'web' failed to build : The command '/bin/sh -c rm -rf node_modules     && npm install node-sass     && cnpm run build' returned a non-zero code: 1

**Comment by awake1t** [comment]
新版本不会报这个错吧

**Comment by magicdvd** [comment]
应该还是有这个问题，跑在windows docker desktop, 应该是WSL2兼容性的问题，和你本身代码无关。 我也在找解决方案，还没找到
