### ISSUE TITLE
请问这个文件在哪配置

### ISSUE THREAD

**Issue by zxs1998** [awake1t/linglong#25]
![微信截图_20210316172057](https://user-images.githubusercontent.com/37968937/111285329-000f4700-867c-11eb-973b-b939d4930251.png)

**Comment by Belee05** [comment]
你这是服务器部署吗？需要修改服务器IP，详情看项目首页的readme

**Comment by zxs1998** [comment]
> 你这是服务器部署吗？需要修改服务器IP，详情看项目首页的自述文件

嗯部署在虚拟机里  这是按照readme里面使用sed命令之后出现的

**Comment by Belee05** [comment]
> > 你这是服务器部署吗？需要修改服务器IP，详情看项目首页的自述文件
> 
> 嗯部署在虚拟机里 这是按照readme里面使用sed命令之后出现的

需要把 YourServerIp 换成你的服务器IP地址

**Comment by zxs1998** [comment]
> > > 你这是服务器部署吗？需要修改服务器IP，详情看项目首页的自述文件
> > 
> > 
> > 嗯部署在虚拟机里 这是按照readme里面使用sed命令之后出现的
> 
> 需要把 YourServerIp 换成你的服务器IP地址

![QQ截图20210317091149](https://user-images.githubusercontent.com/37968937/111399712-dcdaab00-8700-11eb-8b03-b923442c786f.jpg)
你说的是这里吧  我已经用这条命令替换过了

**Comment by awake1t** [comment]
截图大点，你浏览器的地址。还有给下你截图里，红色链接点开的请求细节。  如果服务器部署，记得删除之前部署的容器
