### ISSUE TITLE
Service 'web' failed to build : Error parsing reference: "nginx:1.15.3-alpine as production-stage" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by shellsec** [awake1t/linglong#27]
Service 'web' failed to build : Error parsing reference: "nginx:1.15.3-alpine as production-stage" is not a valid repository/tag: invalid reference format

**Comment by awake1t** [comment]
大概率是你docker版本问题

**Comment by awake1t** [comment]
大概率是你docker 版本，你的docker版本是多少
![image](https://user-images.githubusercontent.com/69112564/112098024-0487b280-8bdc-11eb-90b2-9ecb54034785.png)

https://www.jianshu.com/p/5b01e1534153
