### ISSUE TITLE
设置公网访问IP时，报错【sed: couldn't open temporary file ./dist/js/sedF5BJSs: Permission denied】

### ISSUE THREAD

**Issue by biggun-sw** [awake1t/linglong#30]
设置公网访问IP时，报错【sed: couldn't open temporary file ./dist/js/sedF5BJSs: Permission denied】

但是文件夹下没有这个./dist/js/sedF5BJSs文件

**Comment by awake1t** [comment]
./dist/js/sedF5BJSs 这个命令，不是我项目里的。报错可以百度下

**命令是这个**
# 把 YourServerIp 换成你的IP地址
sed -i 's#http://127.0.0.1:18000#http://YourServerIp:18000#g' ./dist/js/app.4dccb236.js && sed -i 's#http://127.0.0.1:18000#http://YourServerIp:18000#g' ./dist/js/app.4dccb236.js.map
