### ISSUE TITLE
本地docker搭建，静态资源无法加载

### ISSUE THREAD

**Issue by KrystianLi** [awake1t/linglong#47]
本地docker安装启动成功，在访问web服务的时候，页面显示空白，F12查看网络请求发现静态资源没有加载成功，403。这个问题怎么解决
![image](https://user-images.githubusercontent.com/48751812/128689780-314514f8-60e4-4032-8067-66301bb481f4.png)

**Comment by awake1t** [comment]
这是一个权限问题，好像是目录权限。 之前有人微信反馈过
