### ISSUE TITLE
扫描还是无法启动

### ISSUE THREAD

**Issue by shen1in** [awake1t/linglong#49]

**Comment by shen1in** [comment]
![image](https://user-images.githubusercontent.com/68018113/131303219-8c8a5cb4-96b7-4935-8534-b3a23f26bad8.png)
![image](https://user-images.githubusercontent.com/68018113/131303144-b4c602f2-6490-4be1-9dde-961921c40a63.png)
![image](https://user-images.githubusercontent.com/68018113/131303176-57425b9f-6cc4-4e59-884c-75c44953a8f6.png)

**Comment by shen1in** [comment]
请问下师傅这是什么原因

**Comment by awake1t** [comment]
已经在扫了，资产端口太多了。会比较慢
