### ISSUE TITLE
Vue写界面看着就是柔滑好看，请问师傅vue用了多长时间学习然后写的这个界面呢？

### ISSUE THREAD

**Issue by sv3nbeast** [awake1t/linglong#5]

**Comment by awake1t** [comment]
断断续续2周-3个月吧，有点忘了。 一些都是自己写着遇到问题去解决，慢慢学会的。 建议找个视频或者一个系统教程看。 可以跳着看，但要系统，不然后面会有点懵。  个人愚见，仅供参考

**Comment by sv3nbeast** [comment]
OKOK，我正在这个过程，看来和师傅差不多
