### ISSUE TITLE
阿里云部署要更改127.0.0.1地址的吧，我改成外网IP登录也还是没反应。端口全部放行的

### ISSUE THREAD

**Issue by Katsec** [awake1t/linglong#53]

**Comment by awake1t** [comment]
提供F12网络中的请求包截图，环境，部署方式到ISSUE。

**Comment by Katsec** [comment]
> 提供F12网络中的请求包截图，环境，部署方式到ISSUE。

![image](https://user-images.githubusercontent.com/47964489/137071182-c01054b8-afaa-4f98-9abe-c1487bef3007.png)
![image](https://user-images.githubusercontent.com/47964489/137071499-cfc14b74-f5d5-4555-b100-a65bcd9045b0.png)

按照安装提示已经将127.0.0.1 修改为VPS地址

**Comment by Katsec** [comment]
> 提供F12网络中的请求包截图，环境，部署方式到ISSUE。

![image](https://user-images.githubusercontent.com/47964489/137071490-2f699f1b-b3da-4596-a73c-f5d0b615e9d3.png)
