### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by xxsmile123** [awake1t/linglong#54]
环境：ubuntu 18.04.4 ltsc
linglong版本：最新版
部署报错内容如下：
WARNING: Image for service web was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating linglong_mysql_1 ... 
Creating linglong_mysql_1 ... done
Creating linglong-server ... 
Creating linglong-server ... error

ERROR: for linglong-server  Cannot start service server: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./linglong": permission denied: unknown

ERROR: for server  Cannot start service server: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./linglong": permission denied: unknown
ERROR: Encountered errors while bringing up the project.
报错截图：
![image](https://user-images.githubusercontent.com/43473886/141651279-2c3100c0-0b8a-4ae7-bbc0-4d698a8cbf0c.png)

查看启动的docker容器，linlinglong-web未启动

**Comment by awake1t** [comment]
参考 https://github.com/awake1t/linglong/issues/55
