### ISSUE TITLE
账号密码输入后点击无反应

### ISSUE THREAD

**Issue by KKWeName** [awake1t/linglong#58]
如题

**Comment by KKWeName** [comment]
![image](https://user-images.githubusercontent.com/59639656/144377900-934736b8-5a8c-41d7-bb17-89ba250d169a.png)
kali

**Comment by KKWeName** [comment]
> 如题

**Comment by yourbesttao** [comment]
您好！我也是遇到了同样的问题，解决了吗？如何解决
