### ISSUE TITLE
跑不起来...

### ISSUE THREAD

**Issue by KKWeName** [awake1t/linglong#59]
![image](https://user-images.githubusercontent.com/59639656/144380195-77c20c07-d5ef-490f-8c92-6c537e692335.png)
![image](https://user-images.githubusercontent.com/59639656/144380198-72a2c59f-26e8-4d42-9bd1-913f9a0a2030.png)

**Comment by awake1t** [comment]
docker后端服务都正常嘛？

**Comment by KKWeName** [comment]
发现原来是后端问题~
