### ISSUE TITLE
kali 里面 access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by kejaly** [awake1t/linglong#6]
kali 里面 access denied for user 'root'@'localhost'
![image](https://user-images.githubusercontent.com/46043605/103090447-f9000c00-462b-11eb-9ca6-b77f5c66fbad.png)
本地直接 mysql -u root -h localhost -p root 可以登录mysql
而且配置为文件的密码也改成了root 
![image](https://user-images.githubusercontent.com/46043605/103090565-5431fe80-462c-11eb-91cf-7fdbfb3965bf.png)

**Comment by awake1t** [comment]
sudo 运行

**Comment by kejaly** [comment]
> sudo 运行

![image](https://user-images.githubusercontent.com/46043605/103295460-f0924180-4a2e-11eb-9826-6e7f9fdc89e2.png)
sudo 也不行

**Comment by awake1t** [comment]
sudo 运行自己本地mysql客户端连接，看看你账号密码对不对

**Comment by Wwon1oung** [comment]
没设置用户对数据库的操作
首先要使用修改root用户的权限：
1.sudo mysql
2.使用ALTER USER 命令并更改身份验证方法以root身份登录MySQL ：
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'insert_password';

![image](https://user-images.githubusercontent.com/55070231/103769700-bc86d400-505f-11eb-81ee-02492a76711b.png)


此命令更改用户root的密码，并将身份验证方法设置为mysql_native_password。
