### ISSUE TITLE
指纹管理

### ISSUE THREAD

**Issue by fauns-o** [awake1t/linglong#64]
请问指纹管理如何添加，有模板吗
谢谢

**Comment by awake1t** [comment]
看下这个 gif https://github.com/awake1t/linglong/blob/master/img/finger.gif

**Comment by hunter-00** [comment]
![image](https://user-images.githubusercontent.com/67944000/155452378-30516261-ccbe-4602-8d96-66fcc65506a3.png)

熟练使用并且能够看懂这种代码  需要学什么 能不能给个思路 
谢谢

**Comment by fauns-o** [comment]
> 看下这个gif https://github.com/awake1t/linglong/blob/master/img/finger.gif

设备使用并且能够看懂这种代码需要学什么才能给个思路
谢谢

![image](https://user-images.githubusercontent.com/67944000/155452556-99f615a0-f77d-4bd8-8d0e-00c7bbae032d.png)

**Comment by awake1t** [comment]
知道指纹识别原理
知道JSON格式
收工

**Comment by fauns-o** [comment]
> 知道指纹原理 知道JSON格式 收工识别

非常感谢 !!!
