### ISSUE TITLE
请问一下登录的问题

### ISSUE THREAD

**Issue by ddm-alt** [awake1t/linglong#73]

**Comment by ddm-alt** [comment]
![image](https://user-images.githubusercontent.com/89294264/163684113-aa7ef295-38ec-4121-a776-5f478ce2fb44.png)
![image](https://user-images.githubusercontent.com/89294264/163684168-118429b0-0b1c-40a6-87e7-3c4aa00c32a3.png)
![image](https://user-images.githubusercontent.com/89294264/163684185-2976c994-736e-4e27-b0fb-aa83e2cb751d.png)

**Comment by ddm-alt** [comment]
请问师傅，这个如果是 docker 启动的话，直接请求 127.0.0.1 能访问到server 嘛？我通过公网ip加api访问发现是正常的

**Comment by ddm-alt** [comment]
![image](https://user-images.githubusercontent.com/89294264/163686156-d895f2dd-93a1-4ede-aaa3-476e192de55b.png)
师傅我直接到docker里面去执行了命令。替换了
但还是没办法正常登录

**Comment by ddm-alt** [comment]
18000 端口的 server 的docker 我已经正常启动了

**Comment by awake1t** [comment]
问题是sed没有替换成功， 所以会一直访问127的地址。正常成功应该访问你服务器器地址。建议sed后重启容器试试
