### ISSUE TITLE
貌似c段过多就不会扫描

### ISSUE THREAD

**Issue by zuiss** [awake1t/linglong#9]

**Comment by awake1t** [comment]
不会，辛苦等下。masscan设置的扫描速率问题

**Comment by RainClown** [comment]
> 
> 
> 不会，辛苦等下。masscan设置的扫描速率问题

请问运行日志里每个masscan任务都是把设置里所有IP扫了一遍就出一次日志吗，我这边扫全端口实际有很多资产但是日志上的成功数量都是0

**Comment by zuiss** [comment]
> 不会，辛苦等下。masscan设置的扫描速率问题

噢噢，好的，thinks

**Comment by awake1t** [comment]
日志里0，代表这个任务在执行中。是0, 如果扫到了资产。会回来更新这个0的数字。    建议先扫一个C段，top10端口体验下。 后面扫大量数据时，让他跑个一晚上这种。 但是如果资产+端口太多，一天也可能跑不完，masscan原理

**Comment by zuiss** [comment]
还有个问题就是，xray结果那里，时间会随着网页刷新而更新，导致不太好判断时间段。

**Comment by zuiss** [comment]
> 还有个问题就是，xray结果那里，时间会随着网页刷新而更新，导致不太好判断时间段。

网站首页welcome，也有个ui问题，显示了2个一模一样的管理后台。

**Comment by awake1t** [comment]
> 还有个问题就是，xray结果那里，时间会随着网页刷新而更新，导致不太好判断时间段。

收到 谢谢反馈，已加入TODO

**Comment by awake1t** [comment]
> 网站首页welcome，也有个ui问题，显示了2个一模一样的管理后台。

方便给下截图吗

**Comment by zuiss** [comment]
> > 网站首页welcome，也有个ui问题，显示了2个一模一样的管理后台。
> 
> 方便给下截图吗

https://www.hualigs.cn/image/6034a5f624bea.jpg

**Comment by awake1t** [comment]
> > > 网站首页welcome，也有个ui问题，显示了2个一模一样的管理后台。
> > 
> > 
> > 方便给下截图吗
> 
> https://www.hualigs.cn/image/6034a5f624bea.jpg

项目README.MD 就是这样。这里还没想好放啥，就放了一样的。 哈哈。

**Comment by zuiss** [comment]
> > > > 网站首页welcome，也有个ui问题，显示了2个一模一样的管理后台。
> > > 
> > > 
> > > 方便给下截图吗
> > 
> > 
> > https://www.hualigs.cn/image/6034a5f624bea.jpg
> 
> 项目README.MD 就是这样。这里还没想好放啥，就放了一样的。 哈哈。

噢，原来是这样，哈哈哈
